name: Update from main branch

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull
